version: "3.9"
services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=kanban-go
    volumes:
      - db:/var/lib/postgresql/data
  # postgest_test:
  #   image: postgres:16.2
  #   container_name: postgres_test
  #   # restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=db_user_test
  #     - POSTGRES_PASSWORD=12345
  #     - POSTGRES_DB=kanban_go_test_db
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   depends_on:
  #     - database
  #   networks:
  #     - default
  #   ports:
  #     - "8080:8080"
volumes:
  db:
    driver: local
